### ISSUE TITLE
Custom CSS Resource Packs

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#156]
### What solution would you like?

I guess we're making this, but resource packs in CSS or something that can change how the website works

### What alternatives have you considered?

oh we know we are doing this

### What are some pros and cons of doing this?

We already know we are doing this.

### What page is this for?

Twelve of Code

**Comment by BeepBot99** [comment]
I do have some ideas though, I can tell you in the Discord server later.

**Comment by BeepBot99** [comment]
I think something like BetterDiscord, like with CSS custom properties.

**Comment by BeepBot99** [comment]
Or alternatively, it could be JSON or XML.

**Comment by BeepBot99** [comment]
No, it should be that you change everything to CSS variables and then they just make a file with custom properties.

**Comment by Mesure73L** [comment]
Yes, that is what I mean. But, if they change a specific element, like this:
```css
body {
    background-color: #000000;
}
```
then that will not be blocked or anything.

**Comment by BeepBot99** [comment]
Yes, but that does not matter. They can do it the hard way if they want, or they can do it the easy way:
```css
:root {
  --main-color: white;
  --cool-color: white;
  --settings-border-radius: 0;
}
```
However, they could do something like this if they want to be reckless:
```css
*:hover {
display:none;
}
```
Or something else like that. Then, the user would not be able to remove the theme pack without resetting their cookies. So, I think there should be a settings button that is always there no matter what that is like only if you hover over it in the corner so it doesn't take over your screen. But it will bring original settings no matter what.
